const base=process.env.FEES_TEST_API_URL??"http://localhost:43140/api";
async function r(path,{token,method="GET",body}={}){const x=await fetch(base+path,{method,headers:{...(body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:x.status,data:await x.json().catch(()=>null)};}
function ok(v,m){if(!v)throw new Error(m);console.log(`PASS ${m}`)}
async function login(email,password="password123"){const x=await r("/auth/login",{method:"POST",body:{email,password}});ok(x.status===200,`login ${email}`);return x.data.token;}
const stamp=Date.now(),a=await login("everbright.admin@example.com"),b=await login("riverside.admin@example.com"),teacher=await login("everbright.teacher@example.com"),staff=await login("everbright.staff@example.com"),parent=await login("everbright.parent@example.com"),studentToken=await login("everbright.student@example.com"),superToken=await login("superadmin@example.com");
const own=await r("/students/me",{token:studentToken});ok(own.status===200,"student fixture available");const student=own.data;const classA=(await r(`/classes/${student.class_id}`,{token:a})).data;const classB=(await r("/classes",{token:b})).data[0];const studentB=(await r("/students",{token:b})).data[0];
const structure=await r("/fee-structures",{token:a,method:"POST",body:{academicYearId:student.academic_year_id,classId:student.class_id,feeType:`Step7 Tuition ${stamp}`,category:"Tuition",frequency:"Term",amount:12000,dueDate:"2026-09-01",description:"Step 7 verification"}});ok(structure.status===201,"fee structure created");
ok((await r(`/fee-structures/${structure.data.id}`,{token:a,method:"PATCH",body:{description:"Verified structure"}})).status===200,"fee structure updated");ok((await r(`/fee-structures/${structure.data.id}`,{token:b,method:"PATCH",body:{amount:1}})).status===404,"School B cannot update School A fee structure ID");const disposable=await r("/fee-structures",{token:a,method:"POST",body:{academicYearId:student.academic_year_id,feeType:`Disposable ${stamp}`,category:"Other",frequency:"One-Time",amount:1,dueDate:"2027-01-01"}});ok(disposable.status===201&&(await r(`/fee-structures/${disposable.data.id}`,{token:a,method:"DELETE"})).status===200,"unassigned fee structure deleted");
ok((await r("/fee-structures",{token:a,method:"POST",body:{academicYearId:student.academic_year_id,classId:student.class_id,feeType:`Step7 Tuition ${stamp}`,category:"Tuition",frequency:"Term",amount:12000,dueDate:"2026-09-01"}})).status===409,"equivalent structure rejected");
ok((await r("/fee-structures",{token:a,method:"POST",body:{academicYearId:classB.academic_year_id,classId:classB.id,feeType:"Cross",category:"Other",frequency:"Annual",amount:10}})).status===400,"cross-school fee structure relationship rejected");
const structureB=await r("/fee-structures",{token:b,method:"POST",body:{academicYearId:classB.academic_year_id,classId:classB.id,feeType:`Step7 B ${stamp}`,category:"Other",frequency:"One-Time",amount:100}});ok(structureB.status===201,"School B fee structure created");ok(!(await r("/fee-structures",{token:a})).data.some(x=>x.id===structureB.data.id),"structure list remains school scoped");
const assigned=await r("/fees",{token:a,method:"POST",body:{studentId:student.id,feeStructureId:structure.data.id,discount:1000,fine:200}});ok(assigned.status===201,"student fee assigned from applicable structure");const feeId=assigned.data.id;
ok((await r("/fees",{token:a,method:"POST",body:{studentId:student.id,feeStructureId:structure.data.id,discount:1000}})).status===409,"duplicate student fee assignment rejected");ok((await r("/fees",{token:b,method:"POST",body:{studentId:studentB.id,feeStructureId:structure.data.id}})).status===400,"cross-school fee structure assignment rejected");ok((await r("/fees",{token:a,method:"POST",body:{studentId:studentB.id,amount:100}})).status===400,"cross-school student assignment rejected");
let fee=(await r(`/fees?studentId=${student.id}`,{token:a})).data.find(x=>x.id===feeId);ok(fee.total_fee===11200&&fee.outstanding_amount===11200&&fee.overdue_amount===11200&&fee.calculated_status==="Overdue","total, concession, outstanding and overdue calculated authoritatively");
ok((await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:0,method:"Cash"}})).status===400,"zero payment rejected");ok((await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:-1,method:"Cash"}})).status===400,"negative payment rejected");ok((await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:11201,method:"Cash"}})).status===409,"overpayment rejected");
const partial=await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:3000,method:"Cash",transactionReference:`CASH-${stamp}`,idempotencyKey:`idem-${stamp}`,remarks:"First installment"}});ok(partial.status===201&&partial.data.status==="Partial"&&partial.data.remaining===8200,"partial payment recorded atomically");const duplicate=await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:3000,method:"Cash",transactionReference:`CASH-${stamp}`,idempotencyKey:`idem-${stamp}`}});ok(duplicate.status===200&&duplicate.data.receipt_no===partial.data.receiptNo,"idempotency prevents duplicate payment processing");
const payments=await r(`/fees/${feeId}/payments`,{token:a});ok(payments.status===200&&payments.data.length===1,"payment ledger contains one authoritative payment");const receipt=await r(`/fees/receipts/${partial.data.receiptId}`,{token:a});ok(receipt.status===200&&receipt.data.student_name===student.name&&receipt.data.amount===3000&&receipt.data.school_name,"receipt snapshot is retrievable and complete");ok((await r(`/fees/receipts/${partial.data.receiptId}`,{token:b})).status===404,"School B cannot access School A receipt ID");
ok((await r(`/fees/${feeId}/pay`,{token:a,method:"POST",body:{payAmount:1,method:"Cash",transactionReference:`CASH-${stamp}`,idempotencyKey:`different-${stamp}`}})).status===409,"duplicate transaction reference rejected");ok((await r(`/fees/${feeId}/payments`,{token:a})).data.length===1,"failed duplicate payment transaction rolled back fully");ok((await r(`/fees/${feeId}/payments`,{token:b})).status===404,"School B cannot access School A fee ID");ok((await r(`/fees/${feeId}`,{token:b,method:"PATCH",body:{discount:0}})).status===404,"School B cannot update School A fee ID");ok((await r(`/fees/receipts/${partial.data.receiptId}`,{token:studentToken})).status===200,"student can retrieve own receipt");
ok((await r("/fees",{token:parent})).data.some(x=>x.id===feeId),"parent sees linked child's fee");ok((await r(`/fees?studentId=${studentB.id}`,{token:parent})).data.length===0,"parent cannot query unrelated child fees");ok((await r("/fees",{token:studentToken})).data.some(x=>x.id===feeId),"student sees own fee");ok((await r(`/fees/${feeId}/payments`,{token:studentToken})).status===200,"student sees own payment history");ok((await r("/fees",{token:teacher})).status===403,"teacher has no financial access");ok((await r("/fees",{token:staff})).status===403,"non-Accounts staff has no financial access");ok((await r("/fees",{token:superToken})).status===403,"Super Admin is not treated as school finance user");
const staffCreate=await r("/staff",{token:a,method:"POST",body:{employeeId:`ACC-${stamp}`,name:"Step7 Accounts",department:"ACCOUNTS",login:{email:`accounts.${stamp}@example.test`,password:"SecurePass123!"}}});ok(staffCreate.status===201,"Accounts staff fixture created");const accounts=await login(`accounts.${stamp}@example.test`,"SecurePass123!");ok((await r("/fee-structures",{token:accounts})).status===200,"Accounts staff can view fee structures");const finalPay=await r(`/fees/${feeId}/pay`,{token:accounts,method:"POST",body:{payAmount:8200,method:"Bank Transfer",transactionReference:`BANK-${stamp}`,idempotencyKey:`final-${stamp}`}});ok(finalPay.status===201&&finalPay.data.status==="Paid"&&finalPay.data.remaining===0,"Accounts staff records final payment");fee=(await r(`/fees?studentId=${student.id}`,{token:a})).data.find(x=>x.id===feeId);ok(fee.paid_amount===11200&&fee.outstanding_amount===0&&fee.calculated_status==="Paid","paid and outstanding totals reconcile");ok((await r(`/fees/${feeId}`,{token:a,method:"DELETE"})).status===409,"fee with payment history cannot be deleted");ok((await r(`/fee-structures/${structure.data.id}`,{token:a,method:"DELETE"})).status===409,"assigned structure cannot be deleted");const audit=await r("/audit",{token:superToken});ok(audit.status===200&&audit.data.some(x=>x.action==="fee_payment.recorded"),"financial payment audit event recorded");
console.log("Fees and payments integration verification complete.");
