import { Router } from "express";
import { randomUUID } from "node:crypto";
import { db } from "../db/client.js";
import { authenticate, authorize, requireSchoolId } from "../middleware/auth.js";
import { assertParentOwnsStudent, classScopeForUser, inClause, logAudit, studentClassId } from "./helpers.js";
export const examsRouter=Router();examsRouter.use(authenticate);
const TYPES=["Unit Test","Monthly Test","Mid-Term","Half-Yearly","Final","Other"], STATUSES=["DRAFT","MARKS_ENTRY","REVIEW","PUBLISHED","CANCELLED"];
const dateOk=(v:unknown)=>{if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(`${v}T00:00:00Z`);return!Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===v;};
const timeOk=(v:unknown)=>v==null||v===""||(typeof v==="string"&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v));
async function context(schoolId:string,year:unknown,classId:unknown,subjectId:unknown,roomId?:unknown){
 if(![year,classId,subjectId].every(v=>typeof v==="string"&&v))return{error:"academicYearId, classId and subjectId are required"};
 const row=await db.prepare(`SELECT 1 FROM classes c JOIN class_subjects cs ON cs.class_id=c.id AND cs.school_id=c.school_id JOIN subjects s ON s.id=cs.subject_id AND s.school_id=c.school_id WHERE c.id=? AND c.school_id=? AND c.academic_year_id=? AND s.id=?`).get(classId,schoolId,year,subjectId);
 if(!row)return{error:"Class, academic year and subject must be an assigned same-school relationship"};
 if(roomId&&!await db.prepare("SELECT 1 FROM rooms WHERE id=? AND school_id=?").get(roomId,schoolId))return{error:"Room does not belong to this school"};return{ok:true};
}
examsRouter.get("/",authorize("exams.view"),async(req,res)=>{const schoolId=requireSchoolId(req,res);if(!schoolId)return;let{classIds}=await classScopeForUser(req.user!);if(req.user!.role==="PARENT"&&typeof req.query.studentId==="string"){if(!await assertParentOwnsStudent(req.user!,req.query.studentId))return res.status(404).json({error:"Student not found"});const cid=await studentClassId(req.query.studentId);classIds=cid?[cid]:[];}const where=["e.school_id=?"],params:unknown[]=[schoolId];if(classIds!==null){const x=inClause(classIds);where.push(`e.class_id ${x.sql}`);params.push(...x.params);}if(["PARENT","STUDENT"].includes(req.user!.role))where.push("e.status NOT IN ('DRAFT','CANCELLED')");res.json(await db.prepare(`SELECT e.*,s.name subject_name,c.name class_name,c.section,ay.name academic_year_name,r.name room_name FROM exams e LEFT JOIN subjects s ON s.id=e.subject_id LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN academic_years ay ON ay.id=e.academic_year_id LEFT JOIN rooms r ON r.id=e.room_id WHERE ${where.join(" AND ")} ORDER BY e.date,e.start_time`).all(...params));});
examsRouter.get("/:id",authorize("exams.view"),async(req,res)=>{const schoolId=requireSchoolId(req,res);if(!schoolId)return;const exam=await db.prepare("SELECT * FROM exams WHERE id=? AND school_id=?").get(req.params.id,schoolId) as any;if(!exam)return res.status(404).json({error:"Exam not found"});const{classIds}=await classScopeForUser(req.user!);if(classIds!==null&&!classIds.includes(exam.class_id))return res.status(404).json({error:"Exam not found"});if(["PARENT","STUDENT"].includes(req.user!.role)&&["DRAFT","CANCELLED"].includes(exam.status))return res.status(404).json({error:"Exam not found"});res.json(exam);});
examsRouter.post("/",authorize("exams.manage"),async(req,res)=>{const schoolId=requireSchoolId(req,res);if(!schoolId)return;const b=req.body??{};if(!TYPES.includes(b.examType)||!dateOk(b.date)||!timeOk(b.startTime)||!timeOk(b.endTime)||typeof b.name!=="string"||!b.name.trim()||typeof b.maximumMarks!=="number"||b.maximumMarks<=0||typeof b.passingMarks!=="number"||b.passingMarks<0||b.passingMarks>b.maximumMarks)return res.status(400).json({error:"Invalid exam values"});if(b.startTime&&b.endTime&&b.startTime>=b.endTime)return res.status(400).json({error:"End time must be after start time"});const ctx=await context(schoolId,b.academicYearId,b.classId,b.subjectId,b.roomId);if("error"in ctx)return res.status(400).json({error:ctx.error});const subject=await db.prepare("SELECT name FROM subjects WHERE id=?").get(b.subjectId)as any,id=randomUUID();try{await db.prepare(`INSERT INTO exams(id,school_id,academic_year_id,class_id,subject_id,subject,name,exam_type,term,date,start_time,end_time,maximum_marks,passing_marks,room_id,instructions,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,schoolId,b.academicYearId,b.classId,b.subjectId,subject.name,b.name.trim(),b.examType,b.name.trim(),b.date,b.startTime||null,b.endTime||null,b.maximumMarks,b.passingMarks,b.roomId||null,b.instructions||null,"DRAFT",req.user!.id);}catch(e){if(e instanceof Error&&e.message.includes("uq_exam_schedule"))return res.status(409).json({error:"A conflicting exam schedule already exists"});throw e;}await logAudit(req,"exam.created",id,JSON.stringify({classId:b.classId,subjectId:b.subjectId,date:b.date}));res.status(201).json({id});});
examsRouter.patch("/:id",authorize("exams.manage"),async(req,res)=>{const schoolId=requireSchoolId(req,res);if(!schoolId)return;const old=await db.prepare("SELECT * FROM exams WHERE id=? AND school_id=?").get(req.params.id,schoolId)as any;if(!old)return res.status(404).json({error:"Exam not found"});const b=req.body??{},status=b.status??old.status,allowed:Record<string,string[]>={DRAFT:["DRAFT","MARKS_ENTRY","CANCELLED"],MARKS_ENTRY:["MARKS_ENTRY","REVIEW"],REVIEW:["REVIEW","MARKS_ENTRY","PUBLISHED"],PUBLISHED:["PUBLISHED"],CANCELLED:["CANCELLED"]};if(!STATUSES.includes(status))return res.status(400).json({error:"Invalid status"});if(!allowed[old.status]?.includes(status))return res.status(409).json({error:"Invalid exam lifecycle transition"});const v={year:b.academicYearId??old.academic_year_id,classId:b.classId??old.class_id,subjectId:b.subjectId??old.subject_id,date:b.date??old.date,max:b.maximumMarks??old.maximum_marks,pass:b.passingMarks??old.passing_marks,start:b.startTime===undefined?old.start_time:b.startTime,end:b.endTime===undefined?old.end_time:b.endTime,type:b.examType??old.exam_type,name:b.name??old.name,room:b.roomId===undefined?old.room_id:b.roomId};if(!TYPES.includes(v.type)||!dateOk(v.date)||!timeOk(v.start)||!timeOk(v.end)||typeof v.max!=="number"||v.max<=0||typeof v.pass!=="number"||v.pass<0||v.pass>v.max||!String(v.name).trim())return res.status(400).json({error:"Invalid exam values"});if(old.status!=="DRAFT"&&Object.keys(b).some(k=>!["status","instructions"].includes(k)))return res.status(409).json({error:"Schedule can only be edited while draft"});const ctx=await context(schoolId,v.year,v.classId,v.subjectId,v.room);if("error"in ctx)return res.status(400).json({error:ctx.error});const subject=await db.prepare("SELECT name FROM subjects WHERE id=?").get(v.subjectId)as any;await db.prepare(`UPDATE exams SET academic_year_id=?,class_id=?,subject_id=?,subject=?,name=?,exam_type=?,term=?,date=?,start_time=?,end_time=?,maximum_marks=?,passing_marks=?,room_id=?,instructions=?,status=?,updated_at=app_now() WHERE id=? AND school_id=?`).run(v.year,v.classId,v.subjectId,subject.name,String(v.name).trim(),v.type,String(v.name).trim(),v.date,v.start||null,v.end||null,v.max,v.pass,v.room||null,b.instructions===undefined?old.instructions:b.instructions||null,status,req.params.id,schoolId);await logAudit(req,status!==old.status?`exam.status.${status.toLowerCase()}`:"exam.updated",req.params.id);res.json({ok:true});});
examsRouter.delete("/:id",authorize("exams.manage"),async(req,res)=>{const schoolId=requireSchoolId(req,res);if(!schoolId)return;const e=await db.prepare("SELECT status FROM exams WHERE id=? AND school_id=?").get(req.params.id,schoolId)as any;if(!e)return res.status(404).json({error:"Exam not found"});if(e.status!=="DRAFT"||await db.prepare("SELECT 1 FROM results WHERE exam_id=? LIMIT 1").get(req.params.id))return res.status(409).json({error:"Only an unused draft exam can be deleted"});await db.prepare("DELETE FROM exams WHERE id=? AND school_id=?").run(req.params.id,schoolId);await logAudit(req,"exam.deleted",req.params.id);res.json({ok:true});});
